version: '3.7'

services:
  recipe_net_prod:
    build: ./
    image: kzorikov/recipe_net_back:v1
    command: gunicorn recipe_net.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/home/recipe/recipe_net/static/
      - media_value:/home/recipe/recipe_net/media/
    env_file:
      - ./env/.env.prod
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.db
  nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_value:/home/recipe/recipe_net/static/
      - media_value:/home/recipe/recipe_net/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
    depends_on:
      - recipe_net_prod
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_value:
  media_value: