version: '3.7'

services:
  recipe_net_prod:
    build: ./
    image: kzorikov/recipe_net_back:v1
    command: gunicorn _recipe_net_settings_.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/home/recipe/recipe_net/static/
      - media_value:/home/recipe/recipe_net/media/
    env_file:
      - ./env/.env.prod
  celery_recipe_net:
    build: ./
    image: kzorikov/recipe_net_back:v1
    command: celery -A _recipe_net_settings_ worker -l INFO
    restart: always
    depends_on:
      - redis_recipe_net
    env_file:
      - ./env/.env.prod
  celery_beat_recipe_net:
    build: ./
    image: kzorikov/recipe_net_back:v1
    command: celery -A _recipe_net_settings_ beat -l INFO
    restart: always
    depends_on:
      - redis_recipe_net
    env_file:
      - ./env/.env.prod
  flower_recipe_net:
    build: ./
    image: kzorikov/recipe_net_back:v1
    command: celery -A _recipe_net_settings_ flower --port=5566 --url-prefix=recipe_net/flower --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    restart: always
    depends_on:
      - celery_recipe_net
    env_file:
      - ./env/.env.prod
    ports:
      - 5566:5566
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.db
  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - static_value:/home/recipe/recipe_net/static/
      - media_value:/home/recipe/recipe_net/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
    depends_on:
      - recipe_net_prod
  redis_recipe_net:
    image: redis:latest
    restart: always
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_value:
  media_value: