# Generated by Django 3.2.3 on 2021-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(db_index=True, help_text='Product quantity', verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('title',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title', max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe title', max_length=200, verbose_name='Title')),
                ('image', models.ImageField(help_text='Recipe image', upload_to='images/', verbose_name='Image')),
                ('description', models.CharField(help_text='Recipe description', max_length=5000, verbose_name='Description')),
                ('time', models.PositiveSmallIntegerField(db_index=True, help_text='Cooking time(min)', verbose_name='Time')),
                ('slug', models.SlugField(blank=True, help_text='Unique key for url generation', max_length=200, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('title', 'author'),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tag title', max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Unique key for url generation', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('title',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the unit', max_length=50, verbose_name='Title')),
            ],
        ),
    ]
