# Generated by Django 3.2.3 on 2021-06-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='recipes',
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(default=1, help_text='Recipe in the favorites', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api_recipe.recipe', verbose_name='Recipes'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='duplicate_favorites'),
        ),
    ]
