# Generated by Django 3.2.3 on 2021-06-06 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_recipe', '0002_auto_20210604_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(help_text='Recipe in the favorites', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api_recipe.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique key for url generation', null=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Recipe in the purchase list', on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='api_recipe.recipe', verbose_name='Recipe')),
                ('user', models.ForeignKey(help_text='The one who adds to purchase list', on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ('user',),
                'get_latest_by': 'id',
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='duplicate_purchase'),
        ),
    ]
