# Generated by Django 3.2.3 on 2021-06-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipe', '0003_auto_20210606_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(help_text='Recipe description', max_length=50000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Recipe ingredients', related_name='recipes', to='api_recipe.Ingredient', verbose_name='Ingredients'),
        ),
    ]
