# Generated by Django 3.2.3 on 2021-07-09 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_recipe', '0004_auto_20210611_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'get_latest_by': 'id', 'ordering': ('user',), 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'id', 'ordering': ('title',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'get_latest_by': 'id', 'ordering': ('-id',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'get_latest_by': 'id', 'ordering': ('title',), 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(help_text='Product: name + unit', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api_recipe.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(help_text='Product unit', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api_recipe.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Recipe tags', related_name='recipes', to='api_recipe.Tag', verbose_name='Tag'),
        ),
    ]
